# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [4]:
import numpy as np

In [5]:
A = np.random.randint(0, 11, (3, 3))
B = np.random.randint(0, 11, (3, 3))
C = np.random.randint(0, 11, (3, 3))
print(A.dot(B+C))
print(A.dot(B)+A.dot(C))

[[ 92  67 138]
 [172 167 194]
 [205 167 273]]
[[ 92  67 138]
 [172 167 194]
 [205 167 273]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [10]:
print(A.dot(B.dot(C)))
print((A.dot(B)).dot(C))

[[1997 1570 1288]
 [2136 1692 1454]
 [2576 2008 1744]]
[[1997 1570 1288]
 [2136 1692 1454]
 [2576 2008 1744]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [11]:
print(A.dot(B))
print(B.dot(A))

[[128  17 111]
 [142  22 113]
 [176  20 138]]
[[ 56  59  84]
 [ 50  74 112]
 [111 117 158]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [6]:
x = np.random.randint(0, 11, (1, 3))
y = np.random.randint(0, 11, (1, 3))

print(np.transpose(x).dot(y))
print(np.transpose(y).dot(x))

[[27 21  3]
 [27 21  3]
 [72 56  8]]
[[27 27 72]
 [21 21 56]
 [ 3  3  8]]


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [3]:
print((A.dot(B)).T)
print((B.T).dot(A.T))

NameError: name 'A' is not defined

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 